services:
  # --- WebRTC Signaling Server ---
  webrtclogic:
    build:
      context: ./webrtclogic
      dockerfile: Dockerfile
    container_name: webrtc-logic
    ports:
      - "3000:3000"
    restart: unless-stopped

  # --- Backend ---
  rescueguide-backend:
    build: ./RescueGuideDB.WebApp
    container_name: rescueguide-backend
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  # --- Control Center App ---
  cc-frontend:
    build: ./ControlCenterApp/controlcenter-frontend
    container_name: cc-frontend
    ports:
      - "4200:80"
    depends_on:
      - cc-backend

  # --- Client App ---
  client-frontend:
    build: ./ClientApp/clientapp-frontend
    container_name: client-frontend
    ports:
      - "4201:80"
    depends_on:
      - client-backend

networks:
  default:
    name: rescueguide-network