services:
  # --- WebRTC Signaling Server ---
  webrtclogic:
    build:
      context: ./webrtclogic
      dockerfile: Dockerfile
    container_name: webrtc-logic
    ports:
      - "3000:3000"
    restart: unless-stopped

  # --- Backend ---
  rescueguide-backend:
    build:
      context: .  
      dockerfile: RescueGuideDB.WebApp/Dockerfile
    container_name: rescueguide-backend
    ports:
      - "8081:8080" 
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080

  # --- Control Center App ---
  cc-frontend:
    build: ./ControlCenterApp/controlcenter-frontend
    container_name: cc-frontend
    ports:
      - "4200:80"
    depends_on:
      - rescueguide-backend

  # --- Client App ---
  client-frontend:
    build: ./ClientApp/clientapp-frontend
    container_name: client-frontend
    ports:
      - "4201:80"
    depends_on:
      - rescueguide-backend

networks:
  default:
    name: rescueguide-network