@UserBackend_HostAddress = http://localhost:5273

### Test: Sende GPS-Daten als Ersthelfer
POST {{UserBackend_HostAddress}}/api/user/send-location
Content-Type: application/json

{
  "userId": "Helfer_123",
  "latitude": 48.2082,
  "longitude": 16.3738,
  "timestamp": "2023-10-27T14:00:00Z"
}