name: Build and Push Docker Images to GHCR

on:
  push:
    branches:
      - main  # Wird bei jedem Push auf den Main-Branch ausgeführt

env:
  REGISTRY: ghcr.io
  # Dein Image-Pfad wird: ghcr.io/dein-nutzername/projektname
  IMAGE_BASE: ghcr.io/${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        include:
          - image_name: cc-backend
            context: ./controlcenterapp/controlcenter-backend
          - image_name: cc-frontend
            context: ./controlcenterapp/controlcenter-frontend
          - image_name: client-backend
            context: ./clientapp/clientapp-backend
          - image_name: client-frontend
            context: ./clientapp/clientapp-frontend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: OmarAL-Desoky
          password: ${{ secrets.rescueGuideGhcrLogin }}

      - name: Lowercase Registry Path
        id: prep
        run: |
          REPO_LOWER="${GITHUB_REPOSITORY,,}"
          echo "image_base=ghcr.io/${REPO_LOWER}" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.context }}
          push: true
          tags: |
            ${{ steps.prep.outputs.image_base }}/${{ matrix.image_name }}:latest
